### ISSUE TITLE
Drop node 4

### ISSUE THREAD

**Issue by vweevers** [Level/errors#14]

**Comment by ralphtheninja** [comment]
I'm taking all these on now, but I'll push directly to master.

**Comment by vweevers** [comment]
Sure

**Comment by vweevers** [comment]
@ralphtheninja please wait with `abstract-leveldown`, we'll get a merge conflict

**Comment by ralphtheninja** [comment]
https://github.com/Level/errors/commit/150a3c6442d12f16e1578eb2ea1bb4e2069d7354

**Comment by ralphtheninja** [comment]
@vweevers I'll release `2.0.0` on thumbs up.

**Comment by vweevers** [comment]
Actually go ahead with `abstract-leveldown`, because you'll need to release that before others. I'll rebase the `airtap` branch afterwards.

**Comment by ralphtheninja** [comment]
I'll take `abstract-leveldown` next then.
