### ISSUE TITLE
Remove typings?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/errors#15]
cc @MeirionHughes

**Comment by juliangruber** [comment]
what's the context for this?

**Comment by vweevers** [comment]
@juliangruber most TypeScript typings are now housed in the `Level/typings` repo, until they stabilize, and then they'll be moved to DefinitelyTyped. See https://github.com/Level/community/issues/16.

The open question here is whether @MeirionHughes has also moved the typings for `errors` to `Level/typings`. If so, we can remove them from `errors`.

**Comment by vweevers** [comment]
@Level/typescript, cc @danwbyrne: Could you take a look at this, see what needs to happen? Are these typings used at all? Can/should they be moved to DT? Thanks!

**Comment by vweevers** [comment]
We're bumping major anyway due to dropping node 9, so I went ahead and removed the typings (0ad3b37c7e1a634d9af5fa7e62f0b95c896460e6).

**Comment by danwbyrne** [comment]
Sorry for not getting back to you, I don't think the typings are used anywhere since they are on DT already. @vweevers
